server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    username: root
    password: Nagendra@2525
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect